name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      "ImageOS": "ubuntu20"
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28.0.2"
          gleam-version: "1.12.0"
          rebar3-version: "3"
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test
